# Generated by Django 3.0.2 on 2020-01-30 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('followup_wait', models.BigIntegerField(default=2)),
                ('escalation_wait', models.BigIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('type_of_enquiry', models.CharField(choices=[('Sales Enquiry', 'Sales Enquiry'), ('Job Seeker', 'Job Seeker'), ('Media', 'Media')], default='Sales Enquiry', max_length=255, null=True, verbose_name='Type of Enquiry')),
                ('company', models.CharField(max_length=255, null=True, verbose_name='Company')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('role', models.CharField(choices=[('Business Owner/Leader', 'Business Owner/Leader'), ('Media', 'Media'), ('Director HR/Talent Acquisition', 'Director HR/Talent Acquisition'), ('Job Seeker', 'Job Seeker'), ('Recruiter/Sourcer', 'Recruiter/Sourcer')], default='Business Owner/Leader', max_length=60, verbose_name='Role')),
                ('message', models.TextField(null=True)),
                ('positions_to_fill', models.BigIntegerField(default=10)),
                ('service_requirements', models.CharField(max_length=100000, null=True)),
                ('loc_of_hire', models.CharField(max_length=100000, null=True)),
                ('industry', models.CharField(max_length=100000, null=True)),
                ('comp_emp_strength', models.BigIntegerField(default=1)),
                ('form_submission_time', models.CharField(max_length=100000, null=True)),
                ('form_type', models.CharField(max_length=100000, null=True)),
                ('source', models.CharField(blank=True, choices=[('call', 'Call'), ('website', 'Website'), ('email', 'Email'), ('existing customer', 'Existing Customer'), ('partner', 'Partner'), ('public relations', 'Public Relations'), ('compaign', 'Campaign'), ('other', 'Other')], default='website', max_length=255, null=True, verbose_name='Source of Lead')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('assigned_to', models.ManyToManyField(default=1, related_name='lead_assigned_salespersonusers', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lead_leadstage', to='leads.LeadStage')),
            ],
        ),
    ]
