# Generated by Django 3.0.2 on 2020-01-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('type_of_enquiry', models.CharField(choices=[('Sales Enquiry', 'Sales Enquiry'), ('Job Seeker', 'Job Seeker'), ('Media', 'Media')], default='Sales Enquiry', max_length=255, verbose_name='Type of Enquiry')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('Business Owner/Leader', 'Business Owner/Leader'), ('Media', 'Media'), ('Director HR/Talent Acquisition', 'Director HR/Talent Acquisition'), ('Job Seeker', 'Job Seeker'), ('Recruiter/Sourcer', 'Recruiter/Sourcer')], default='Business Owner/Leader', max_length=60, verbose_name='Role')),
                ('message', models.TextField()),
                ('positions_to_fill', models.BigIntegerField()),
                ('service_requirements', models.CharField(max_length=100000)),
                ('loc_of_hire', models.CharField(max_length=100000)),
                ('industry', models.CharField(max_length=100000)),
                ('comp_emp_strength', models.BigIntegerField()),
                ('form_submission_time', models.CharField(max_length=100000)),
                ('form_type', models.CharField(max_length=100000)),
                ('status', models.CharField(blank=True, choices=[('not updated', 'Not Updated'), ('BD call', 'BD Call'), ('meeting', 'Meeting'), ('proposal', 'Proposal')], default='not updated', max_length=255, null=True, verbose_name='Status of Lead')),
                ('source', models.CharField(blank=True, choices=[('call', 'Call'), ('website', 'Website'), ('email', 'Email'), ('existing customer', 'Existing Customer'), ('partner', 'Partner'), ('public relations', 'Public Relations'), ('compaign', 'Campaign'), ('other', 'Other')], default='website', max_length=255, null=True, verbose_name='Source of Lead')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
