# Generated by Django 3.0.2 on 2020-01-28 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0002_lead_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='isActive',
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ManyToManyField(default=1, related_name='lead_assigned_salespersonusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='comp_emp_strength',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(max_length=255, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='form_submission_time',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='form_type',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='industry',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='loc_of_hire',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='positions_to_fill',
            field=models.BigIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service_requirements',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='type_of_enquiry',
            field=models.CharField(choices=[('Sales Enquiry', 'Sales Enquiry'), ('Job Seeker', 'Job Seeker'), ('Media', 'Media')], default='Sales Enquiry', max_length=255, null=True, verbose_name='Type of Enquiry'),
        ),
    ]
