# Generated by Django 3.0.3 on 2020-02-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200203_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Updated', 'Not Updated'), ('BD Call', 'BD Call'), ('Meeting', 'Meeting'), ('Proposal', 'Proposal')], default='not updated', max_length=255, null=True, verbose_name='Status of Lead'),
        ),
    ]
