# Generated by Django 3.0.2 on 2020-01-30 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('event_type', models.CharField(choices=[('New Lead', 'New Lead'), ('Lead Status Change', 'Lead Status Change'), ('Regular Follow up', 'Regular Follow up'), ('Escalation', 'Escalation')], max_length=255, verbose_name='Type of Event')),
                ('due_time', models.DateTimeField()),
                ('lead_event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lead_event', to='leads.Lead')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lead_assigned_manager', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lead_assigned_salesperson', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
